export enum ResponseMessageEnum {
  RESOURCE_NOT_FOUND = '资源不存在',
  SYSTEM_RESOURCE_OPERATE = '系统内置资源不能操作',
  CODE_ALREADY_EXISTS = 'code编码已存在',
  ROLE_NAME_ALREADY_EXISTS = '角色名已存在',
  USERNAME_ALREADY_EXISTS = '用户名已存在',
  PHONE_NUMBER_ALREADY_EXISTS = '手机号已存在',
  PHONE_NUMBER_INCORRECT = '手机号不正确',
  PASSWORD_ERROR = '密码错误',
  USER_DISABLED = '用户已禁用',
  USER_NOT_FOUND = '用户不存在',
  INVALID_REFRESH_TOKEN = '无效的刷新令牌',
  PLEASE_LOGIN_FIRST = '请先登录后再操作',
  LOGIN_STATUS_INVALID = '您的登陆状态有误，请重新登录',
  UPDATE_USER_FAILED = '更新用户失败',
  NO_RESOURCES_TO_OPERATE = '没有要操作的资源',
  BATCH_DUPLICATE_IDS = '批量操作包含重复的ID',
  BATCH_DUPLICATE_CODES = '批量操作包含重复的Code',
  SOME_RESOURCES_NOT_FOUND = '部分资源未找到',
  NO_RESOURCES_FOUND = '未找到资源',
}
