# .github/workflows/trigger-deploy.yml
# 构建 r3-admin-server 镜像并触发中央部署

name: Build and Trigger Deployment for r3-admin-server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/r3-admin-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger deployment in app-deployment repo
        if: success()
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CROSS_REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/qyhever/app-deployment/dispatches \
            -d '{"event_type":"deploy-r3-admin-server", "client_payload": {"service": "r3-admin-server"}}'